import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar"
import Footer from "./components/Footer/Footer"
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import Providers from "./components/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> <Providers><Navbar/>
      <Theme accentColor="orange" radius="full">
<main className="p-5">{children}</main>
<Footer/>
</Theme>
</Providers>

</body>

    </html>
  );
}
